# Generated by Django 4.1 on 2023-01-06 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofileinfo",
            name="first_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofileinfo",
            name="last_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofileinfo",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdOn", models.DateTimeField(auto_now_add=True, null=True)),
                ("updatedOn", models.DateTimeField(null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
