# Generated by Django 4.1 on 2023-01-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_userprofileinfo_password"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofileinfo", name="first_name",),
        migrations.RemoveField(model_name="userprofileinfo", name="last_name",),
        migrations.RemoveField(model_name="userprofileinfo", name="password",),
    ]
