# Generated by Django 4.2.1 on 2023-10-27 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0004_remove_userprofileinfo_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='createdBy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
